### ISSUE TITLE
[Bug] Miner page problem 

### ISSUE THREAD

**Issue by xxrobinch** [0LNetworkCommunity/carpe#204]
Since yesterday my mint doesnt change, i press several times use playlist but nothing 
![image](https://github.com/0LNetworkCommunity/carpe/assets/159882637/2ebedc74-195a-4bd1-9ee3-6e905453ee91)

**Comment by RBcryptoking** [comment]
I have the same problem. I will try to explain what the problem is, and what I have done. I have not solved the problem. 

When you slide the button to green under "miner" or go to "miner" tab, all other functions dosent work. All under the green slider is also white. You can click on the slide button under "miner" so it turns red/green, but that is all the works.

Im using windows 10 and carpe v 1.0.0 

What I have tried to solve the problem: 
- Uninstalled carpe and reinstalled
- Switched to english
- Turned of all anti virus
- VPN used for another country
- Give the app 1 hour time, but nothing happened
- Used all update and playlist functions on carpe app

Still nothing works

**Comment by RBcryptoking** [comment]
For me it seems like an interface (front end) problem.

**Comment by ghost** [comment]
See https://github.com/0LNetworkCommunity/carpe/issues/224

**Comment by kalvkusk** [comment]
Mining is sunsetted.
