### ISSUE TITLE
[Bug] Address Change and Missing Funds after Wallet Update

### ISSUE THREAD

**Issue by KeramxD** [0LNetworkCommunity/carpe#205]
After updating my wallet, I've noticed that my address has changed (for longer characters one) and my funds are no longer visible. The correct address and balance were present in Carpe v0.5.0. However, in the latest versions of Carpe and 0ollet, despite using the same seed, a different address is being displayed.

**Comment by Teisson** [comment]
Hi Keram, can you please back up your authkey and such, ie the user related files to make sure you don't overwrite them in the process of upgrading to v1.0.0-18.

The directory usually looks a little bit like this: 

C:\Users\YOUR_USER\.0L

Once you've done that you may need to retrieve your private key using either your cmd prompt or LaZagne which you can find here: 

https://github.com/AlessandroZ/LaZagne 

In order to retrieve the account manually.

If you need support along the way lmk!

**Comment by Teisson** [comment]
A little more information on the issue:
https://0l.fyi/accounts/1C69FC2C5211343850B38790BFAC39F6C821946F926A4AB323BBFD0C96F93D4E
https://0l.fyi/account
![IMG_1041](https://github.com/0LNetworkCommunity/carpe/assets/97843018/b4b59212-7fd6-4558-9104-018e8df2134f)
s/C821946F926A4AB323BBFD0C96F93D4E

**Comment by Teisson** [comment]
@0xzoz

**Comment by 0o-de-lally** [comment]
Try this branch for a PR:
https://github.com/0o-de-lally/libra-framework/blob/reject-legacy-addr-creation/framework/libra-framework/sources/ol_sources/ol_account.move#L240

**Comment by kalvkusk** [comment]
@KeramxD is this still relevant?

**Comment by BBK8530** [comment]
@kalvkusk   His account is on the affected list.

<img width="762" alt="image" src="https://github.com/0LNetworkCommunity/carpe/assets/10484741/2a2c9324-fbd2-46e5-a4a3-a9d84a2e2581">

**Comment by kalvkusk** [comment]
@KeramxD reach out to JudasDayGame in discord. Closing.
